language: python

before_install:
#  - sudo apt-get install python-setuptools
#  - sudo add-apt-repository -y ppa:adrienverge/ppa
#  - sudo apt-get update -q
#  - sudo apt-get install yamllint
  - pip install yamllint

install:
  - pip install -r requirements.txt

script:
  - yamllint docs/includes/examples
  - cd docs && make html
